name: "Maven MultiModule Dependency Submission"
on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '35 9 * * 6'
  workflow_dispatch:
  
jobs:
  tree:
    name: Maven Multi Dependency Submission
    runs-on: ubuntu-20.04
    
    # The API requires write permission on the repository to submit dependencies (HTTP Status 403 for request POST https://api.github.com/repos/vulna-felickz/mvnexbook-examples-1.0/dependency-graph/snapshots)
    permissions:
      actions: read
      contents: write
      
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - run: mvn --version
      
# Reproducing a bug - delete me
# - name: Submit Web Dependency Snapshot
#      uses: advanced-security/maven-dependency-submission-action@v2.0.1
#      with:
#        directory: "./"
        
    - name: Submit Web Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@multi-module
      with:   
        directory: "./ch-multi/"
        snapshot-include-file-name: true
        snapshot-dependency-file-name: "./ch-multi/pom.xml"
